### ISSUE TITLE
Add option for user to modify color theme

### ISSUE THREAD

**Issue by samuelfox1** [chomieu/Voicely#22]
- [x] slide bar or drop down list?
- [x] color variable holding keyword for 'default' user setting
- [x] create an array of color options keywords
- [x] loop to check if keyword matches, if not upgrade keyword to current value
- [x] swap out color key word and refresh page
- [x] remove attribute and replace attribute

**Comment by tmkeller** [comment]
Chomie knocked this one out. Safe to close, I think.
